language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "lts/*"
# before_install:
# before_script:
script:
  - yarn lint
  - yarn build
  - yarn test
# after_success:
#   - yarn report-coverage
